import type {Metadata} from "next";
import {Geist, Geist_Mono, Inter} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import {ThemeProvider} from "@/components/shared/theme-provider"
import {EnvironmentBanner} from "@/components/shared/environment-banner";
import {TooltipProvider} from "@/components/ui/tooltip";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Required for EnvironmentBanner to work at all. In a statically rendered segment Next.js
// evaluates process.env at BUILD time, so APP_ENV_LABEL would be frozen to whatever the
// image was built with -- empty -- and staging would never show its banner. Forcing
// dynamic rendering moves that read to request time, which is the whole point of keeping
// the environment out of the image.
//
// The cost is that the pages under this layout are server-rendered per request instead of
// prerendered. For a three-page login portal that fetches nothing at render time, that is
// negligible; the dashboard was already dynamic because it reads the jwt cookie.
export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <EnvironmentBanner />
          <TooltipProvider>{children}</TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
